# fly.toml app configuration file generated for forest-game on 2023-07-12T23:30:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "forest-game"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
